#!/bin/sh
# /etc/rc.d/transmission: start/stop transmission

case $1 in
	start) /usr/bin/transmission-daemon -e /var/log/transmission ;;
	stop) kill -9 $(pidof /usr/bin/transmission-daemon) ;;
	restart) $0 stop; sleep 2; $0 start ;;
	*) echo "Usage: $0 [start|stop|restart]" ;;
esac
