#!/bin/sh

xset s off
xset -dpms
xset +fp ~/.fonts
xsetroot -name background
xsetroot -cursor_name left_ptr

bar
keys
urxvtd -q -o -f &

test -f ~/.Xresources && xrdb -load ~/.Xresources

exec runfyre
