#!/bin/sh

xset s off
xset -dpms
xset +fp ~/.local/share/fonts
xsetroot -name background
xsetroot -cursor_name left_ptr

keys
infobar
urxvtd -q -o -f &

test -f ~/.Xresources && xrdb -load ~/.Xresources

test $(hostname) = "flame" && {
    synergys
} || {
    synergyc flame
}

exec runfyre
