#!/bin/sh

. ~/.zsh/environment.zsh

MINIMAL="$HOME/.minimal-dotfiles"

cd $MINIMAL || {
    git clone git@github.com:wildefyr/minimal-dotfiles .minimal-dotfiles
}

rsync -arq $DOTS/bin $DOTS/git $DOTS/vim $DOTS/zsh $DOTS/tmuxinator $MINIMAL

cd "$MINIMAL"
git add . && git commit -m "$(date +%D): latest"
git push || exit 130
